# ####################################### #
# ?????????????????????? #
# ####################################### #
# ??????
server:
  # Servlet?Java?????????????
  servlet:
    # ????
    encoding:
      # ?????????
      force: true
      # ???
      charset: UTF-8

# Spring???
spring:
  # Profile???
  profiles:
    # ????Profile??
    active: dev
  # Jackson?????
  jackson:
    # ???JSON?????????????
    default-property-inclusion: non_null

# MyBatis Plus??
mybatis-plus:
  # ??SQL???XML?????
  mapper-locations: classpath:mappers/**/*.xml

# Knife4j??
knife4j:
  # ??????
  enable: true
