# ################################################################################################# #
# 此文件是【开发环境】的配置文件，必须在主配置中通过spring.profiles.active激活此配置，此文件中的各配置才会生效 #
# ################################################################################################# #

# 服务器的配置
server:
  # 服务占用的端口
  port: 9088

# Spring的配置
spring:
  # 数据源的配置
  datasource:
    # 连接数据库的URL
    url: jdbc:mysql://localhost:3306/zhipian_shop?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    # 数据库用户名
    username: root
    # 数据库密码
    password: root
    # Druid连接池的配置
    druid:
      # 初始化连接数量
      initial-size: 5
      # 最大激活数量
      max-active: 20


  web:
    resources:
      static-locations: file:${filePath},classpath:static
logging:
  # 显示级别
  level:
    # 某根包（配置将应用于此包及子孙包）的显示级别
    cn.tedu.back: trace



back.stage.management:
  # 数据访问的相关配置
  dao:
    # 查询数据时，默认的每页记录数，建议值为10~30之间
    default-query-page-size: 5

#自定义配置
zhipian_shop:
  #数据访问的相关配置
  dao:
    #默认页数为5
    default-query-page-size: 5
    cn.tedu.back: trace

filePath: e:/files

# Minio配置
minio:
  endpoint: http://192.168.11.58:9000 #http://192.168.31.234:9000 #
  accessKey: minioadmin
  secretKey: minioadmin
